version: 1.4.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '1.4.0-alfa{build}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    only:
    - CNUnit.Test.dll
artifacts:
- path: '**\CNUnit*.nupkg'
 